.\"                                      Hey, EMACS: -*- nroff -*-
.TH ANAGRAMARAMA 6  "January  4, 2005"
.SH NAME
anagramarama \- cute anagram game using SDL
.SH SYNOPSIS
.B anagramarama
.RI
.br
.SH DESCRIPTION
.B anagramarama
is a simple wordgame in which one tries to guess all the different
permutations of a scrambled word which form another word within the
time limit.  Guess the original word and you move on to the next
level.
.PP
.SH OPTIONS
None, currently.
.br
.SH AUTHOR
anagramarama was written by Colm Gallagher <colm@coralquest.com>
.PP
This manual page was written by Ryan Stutsman <rstutsma@purdue.edu>,
for the Debian project (but may be used by others).
